services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./user_consts.py:/workspace/user_consts.py:ro
#    depends_on:
#      selenium:
#        condition: service_started
#        restart: true
#        required: true
#    environment:
#      - SELENIUM_URL=http://selenium:4444/wd/hub
