on:
    push: 
        branches: 
            -
                main
    pull_request:
permissions:
    contents: read
    packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
    build-base:
        name: Build base image
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        name=${{ env.IMAGE_NAME }}
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: Dockerfile
                    pull: true
                    push: ${{ github.event_name == 'push' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}